objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/InvoiceA__c.object
<CustomObject>
    <fields>
        <fullName>AmountPaid__c</fullName>
        <label>AmountPaid</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>InvoicesA</relationshipLabel>
        <relationshipName>InvoicesA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>InvoiceA</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InvoicesA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ApexInsert.cls
public class ApexInsert {
    public static void demo()
    {
        Customer__c objcust = new Customer__c();
        objcust.name = 'Test ABC';
        //objcust.Active__C = 'N';
        insert objcust;
        InvoiceA__c objinv = new InvoiceA__c();
        objinv.AmountPaid__c = 2000;
        objinv.Customer__c = objcust.id;
        objinv.Description__c = 'This is added from Code';
        insert objinv;
    }

}