objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <label>ExternalId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpsertDemo.cls
public class UpsertDemo {
	public  void demo()
    {
        list <customer__c> custUps = new list <customer__c>();
        customer__c c = [select ExternalId__c,name,Description__c,Status__c from customer__c where ExternalId__c = '1234'];
        c.Description__c = 'This is an update from Apex Code';
        c.Status__c = 'Paid';
        custUps.add(c);
        for(integer i=1;i<=10;i++)
        {
            customer__c c1 = new customer__c(name = 'Test ABC'+i,ExternalId__c = '1234'+i);
            custUps.add(c1);
        }
        upsert custUps;
    }
}