objects/InvoiceA__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>InvoiceA</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InvoicesA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Apex_DMLDemo.cls
public class Apex_DMLDemo {
    Public Static void demo()
    {
        List<InvoiceA__c> invoice = [select id,name,Status__c from InvoiceA__c];
        List <InvoiceA__c> upd = new List<InvoiceA__c>();
        for(InvoiceA__c obj:invoice)
        {
            if(obj.Status__c !='Paid')
            {
                obj.Status__c = 'Paid';
                upd.add(obj);
            }
        }
        update upd;
    }
}