objects/PrivateObject__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>POName__c</fullName>
        <label>POName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>PrivateObject</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>RecordID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrivateObjects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/InsertDemoApex.cls
public class InsertDemoApex {

    Public static void display()
    {
        PrivateObject__c	 p = new PrivateObject__c(POName__c = 'POAPEX-0008');
        Insert p;
        PrivateObject__c  p2 = [select POName__c from PrivateObject__c where POName__c like 'POAPEX-000%' limit 1];
        try{
            string s =p2.Description__c;}
        catch(sObjectException e)
        {
            system.debug('Exception Message'+e.getMessage());
        }
        
    }
}